import { LayoutSection, Product } from "@/lib/types";

export const seedLayout: LayoutSection[] = [
  {
    section_id: "nav-principal",
    area: "header",
    section_type: "navbar",
    title: "COMETA G",
    subtitle: "Computación Gamer",
    order: 1,
    visible: true,
    accent_color: "#E143A6"
  },
  {
    section_id: "header-categorias",
    area: "header",
    section_type: "category_nav",
    text: "Inicio|/,Productos|/productos,Placas de video|/productos?categoria=Placas%20de%20video,Procesadores|/productos?categoria=Procesadores,Monitores|/productos?categoria=Monitores,Preventa|/productos?disponibilidad=preventa",
    order: 2,
    visible: true
  },
  {
    section_id: "hero-home",
    area: "body",
    section_type: "main_banner",
    title: "Hardware gamer listo para despegar",
    subtitle: "Componentes, periféricos y equipos seleccionados para jugar, crear y competir.",
    text: "Compra online o reserva lanzamientos en preventa con stock claro y precios actualizados desde Google Sheets.",
    image_url: "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=1400&q=80",
    link_url: "/productos",
    button_text: "Ver catálogo",
    order: 10,
    visible: true,
    background_color: "#07070A",
    text_color: "#F8F8FF",
    accent_color: "#E5264E",
    layout_variant: "split",
    carousel_enabled: true,
    autoplay: true
  },
  {
    section_id: "promo-cards-home",
    area: "body",
    section_type: "promo_tile_grid",
    text: "Catch big|Hot deals in GPUs|https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=500&q=80|/productos?categoria=Placas%20de%20video|Shop now;The new|Gaming PCs|https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=500&q=80|/productos|Ver equipos;Monitores|QHD y más|https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=500&q=80|/productos?categoria=Monitores|Ver más;Periféricos|RGB sobrio|https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=500&q=80|/productos?categoria=Perifericos|Comprar",
    order: 20,
    visible: true
  },
  {
    section_id: "beneficios-home",
    area: "body",
    section_type: "service_strip",
    text: "Envío rápido|a todo el país;Soporte gamer|asesoría de compra;Garantía oficial|productos seleccionados;Pago seguro|checkout preparado;Solo marcas top|stock actualizado",
    order: 25,
    visible: true
  },
  {
    section_id: "strip-oferta",
    area: "body",
    section_type: "promo_strip",
    title: "Preventa activa",
    text: "Reserva GPUs, monitores y notebooks seleccionadas antes de su lanzamiento.",
    link_url: "/productos?disponibilidad=preventa",
    button_text: "Reservar ahora",
    order: 26,
    visible: false
  },
  {
    section_id: "categorias-home",
    area: "body",
    section_type: "category_grid",
    title: "Compra por categoría",
    subtitle: "Atajos directos a lo que más se busca.",
    order: 30,
    visible: false,
    desktop_columns: 4,
    mobile_columns: 2
  },
  {
    section_id: "destacados-home",
    area: "body",
    section_type: "product_tabs",
    title: "Productos destacados",
    text: "Featured Products|destacado|active;Latest Products|;Sale Products|oferta",
    order: 40,
    visible: true,
    desktop_columns: 5,
    mobile_columns: 2,
    taxonomies_filter: "destacado"
  },
  {
    section_id: "texto-admin",
    area: "body",
    section_type: "text_block",
    title: "Contenido editable desde Sheets",
    text: "Orden, visibilidad, textos, colores, banners, grillas, categorias y filtros salen de la hoja LAYOUT. Productos, precios, stock y preventas salen de PRODUCTOS.",
    order: 50,
    visible: true,
    layout_variant: "compact"
  },
  {
    section_id: "footer-links",
    area: "footer",
    section_type: "footer_links",
    title: "COMETA G",
    text: "Catálogo|/productos,Carrito|/carrito,Wishlist|/wishlist,Login|/login",
    order: 90,
    visible: true
  },
  {
    section_id: "footer-contact",
    area: "footer",
    section_type: "footer_contact",
    title: "Computación Gamer",
    text: "Ventas online, reservas y asesoramiento gamer.",
    order: 100,
    visible: true
  }
];

export const seedProducts: Product[] = [
  {
    id: "p-001",
    sku: "CG-GPU-4070S",
    nombre: "NVIDIA GeForce RTX 4070 Super 12GB",
    slug: "nvidia-geforce-rtx-4070-super-12gb",
    descripcion_corta: "GPU de alto rendimiento para 1440p, ray tracing y creación de contenido.",
    descripcion_larga: "Placa de video ideal para setups gamer modernos, con soporte para DLSS, ray tracing y flujos exigentes de streaming.",
    precio: 899999,
    precio_oferta: 849999,
    stock: 6,
    stock_status: "disponible",
    categoria: "Placas de video",
    subcategoria: "NVIDIA",
    marca: "NVIDIA",
    tags: ["gpu", "rtx", "destacado"],
    imagen_principal: "https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=900&q=80",
    imagenes_extra: [],
    atributos: { Memoria: "12GB GDDR6X", Uso: "Gaming 1440p" },
    variables: undefined,
    color: "Negro",
    garantia: "12 meses",
    destacado: true,
    preventa: false,
    visible: true,
    orden: 1
  },
  {
    id: "p-002",
    sku: "CG-CPU-R7-7800X3D",
    nombre: "AMD Ryzen 7 7800X3D",
    slug: "amd-ryzen-7-7800x3d",
    descripcion_corta: "Procesador AM5 con 3D V-Cache, una bestia sobria para gaming competitivo.",
    descripcion_larga: "CPU gamer de 8 núcleos orientada a alto FPS, eficiencia y plataformas escalables AM5.",
    precio: 539999,
    stock: 4,
    stock_status: "disponible",
    categoria: "Procesadores",
    subcategoria: "AMD AM5",
    marca: "AMD",
    tags: ["cpu", "gaming", "destacado"],
    imagen_principal: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=900&q=80",
    imagenes_extra: [],
    atributos: { Nucleos: "8", Socket: "AM5" },
    color: "Gris",
    garantia: "36 meses",
    destacado: true,
    preventa: false,
    visible: true,
    orden: 2
  },
  {
    id: "p-003",
    sku: "CG-MON-27-QHD",
    nombre: "Monitor Gamer 27 QHD 180Hz",
    slug: "monitor-gamer-27-qhd-180hz",
    descripcion_corta: "Panel QHD rápido para juegos competitivos y escritorio amplio.",
    descripcion_larga: "Monitor equilibrado para jugar, editar y trabajar con frecuencia alta, baja latencia y buena definición.",
    precio: 419999,
    precio_oferta: 389999,
    stock: 0,
    stock_status: "preventa",
    categoria: "Monitores",
    subcategoria: "QHD",
    marca: "Cometa Select",
    tags: ["monitor", "qhd", "preventa"],
    imagen_principal: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80",
    imagenes_extra: [],
    atributos: { Resolución: "2560x1440", Frecuencia: "180Hz" },
    color: "Negro",
    garantia: "12 meses",
    destacado: true,
    preventa: true,
    fecha_lanzamiento: "2026-07-15",
    visible: true,
    orden: 3
  },
  {
    id: "p-004",
    sku: "CG-KEY-RGB-TKL",
    nombre: "Teclado Mecanico TKL RGB",
    slug: "teclado-mecanico-tkl-rgb",
    descripcion_corta: "Formato compacto, switches lineales y RGB sobrio configurable.",
    descripcion_larga: "Teclado mecanico para setups gamer compactos, con buena respuesta y construcción firme.",
    precio: 92999,
    stock: 12,
    stock_status: "disponible",
    categoria: "Perifericos",
    subcategoria: "Teclados",
    marca: "Redragon",
    tags: ["teclado", "rgb"],
    imagen_principal: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=900&q=80",
    imagenes_extra: [],
    atributos: { Formato: "TKL", Switches: "Lineales" },
    color: "Negro",
    garantia: "6 meses",
    destacado: false,
    preventa: false,
    visible: true,
    orden: 4
  },
  {
    id: "p-005",
    sku: "CG-SSD-2TB-NVME",
    nombre: "SSD NVMe 2TB Gen4",
    slug: "ssd-nvme-2tb-gen4",
    descripcion_corta: "Almacenamiento rápido para juegos pesados, edición y cargas casi instantáneas.",
    descripcion_larga: "Unidad NVMe PCIe Gen4 con gran capacidad para bibliotecas modernas y flujo de trabajo exigente.",
    precio: 179999,
    stock: 0,
    stock_status: "sin_stock",
    categoria: "Almacenamiento",
    subcategoria: "NVMe",
    marca: "Kingston",
    tags: ["ssd", "nvme"],
    imagen_principal: "https://images.unsplash.com/photo-1597138804456-e7dca7f59e21?auto=format&fit=crop&w=900&q=80",
    imagenes_extra: [],
    atributos: { Capacidad: "2TB", Interfaz: "PCIe Gen4" },
    color: "Negro",
    garantia: "36 meses",
    destacado: false,
    preventa: false,
    visible: true,
    orden: 5
  }
];
